### ISSUE TITLE
Document steps for installing the extension

### ISSUE THREAD

**Issue by fgeierst** [s2b/vite-asset-collector#1]
First off, the extension works great - awesome work!!

To get it running, I needed to do some additional things. I think it would be useful to somehow add these to the readme. Here is my initial list of steps:

- install [ddev-viteserve](https://github.com/torenware/ddev-viteserve) `ddev get torenware/ddev-viteserve`
- configure ddev-viteserve in .ddev/.env
- initialize npm package `ddev npm init -y`
- add pnpm ddev command
- ddev post-start hook
- vite config file
- install helhum/dotenv-connector
- set `TYPO3_CONTEXT="Development"` in .env file
- add vite assets to. gitignore
- asset.vite viewhelper in layout html file

I made a [demo TYPO3 12 project](https://github.com/fgeierst/typo3-vite-asset-collector-demo), and the steps mostly correspond to [this commit](https://github.com/fgeierst/typo3-vite-asset-collector-demo/commit/79d0963530b59d7e5a4e367d49db3cc6fa7d9008).

**Comment by s2b** [comment]
First of all, thank you for testing the extension! :)

I've been experimenting with a more generic version of this. I think that TYPO3 setups are just too different (e. g. concerning the structure of sitepackages) to give a simple demo instruction. Instead, I added a broader documentation which covers the necessary setup steps:

https://github.com/s2b/vite-asset-collector/blob/main/Documentation/DdevSetup.md

**Comment by fgeierst** [comment]
Perfect! I think that resolves it.

Some small enhancement would be to link to [ddev-viteserve](https://github.com/torenware/ddev-viteserve) repo in [DdevSetup.md](https://github.com/s2b/vite-asset-collector/blob/main/Documentation/DdevSetup.md), too.

And maybe mention that Vite itself needs to be installed with NPM, either through the scaffolding CLI [create-vite](https://github.com/vitejs/vite/tree/main/packages/create-vite) or with `npm install -D vite`.

**Comment by s2b** [comment]
Fixed, thanks!
