### ISSUE TITLE
[QUESTION] What is the best practice for extension assets

### ISSUE THREAD

**Issue by Tim-Obert** [s2b/vite-asset-collector#100]
I have a site that uses e.g. solr and jQuery in the sitepackage. 
I am adding jQuery through the Sitepackage. So it needs to be loaded after the script in the sitepackage. 

What is the best practice for assets, that are included via TypoScript? 
Remove them from TypoScript and add the path in the Bundle or is there another way?

**Comment by s2b** [comment]
I would try to remove every library or other JS include from TypoScript if that's at all possible. That way you can decide for each page if that library is really necessary and you can try to fade it out file by file.

Sometimes you might need to apply some "hacks" through your vite config, like:

```js
export default defineConfig({
    build: {
        rollupOptions: {
            output: {
                globals: {
                    'jQuery': 'window.jQuery',
                    '$': 'window.$',
                },
            },
        },
```

This might be necessary for certain jQuery plugins that depend on the global `$`. Other than that it should be possible to import jQuery into your ES module like any other dependency:

```js
import $ from "jquery";
```
