### ISSUE TITLE
Different handling of paths with dev and build (font inclusion)

### ISSUE THREAD

**Issue by fjacobi** [s2b/vite-asset-collector#14]
Hej, I'm adapting a template with a grunt build into vite to prepare for an TYPO3 upgrade further down the line.

Folder layout:
```
/packages/sitepackage/
/frontend/vite.config.js
/frontend/main.js
/frontend/main.scss
/frontend/sandbox/scss/style
```

vite.config.js
```
import { defineConfig } from 'vite'
import { resolve } from 'path'

// TYPO3 root path (relative to this config file)
const VITE_TYPO3_ROOT = "./../";

// Vite input files (relative to TYPO3 root path)
const VITE_ENTRYPOINTS = [
    "frontend/main.js",
];

// Output path for generated assets
const VITE_OUTPUT_PATH = "packages/sitepackage/Resources/Public/build/";

const rootPath = resolve(__dirname, VITE_TYPO3_ROOT);

export default defineConfig({
    base: '',
    build: {
        manifest: true,
        rollupOptions: {
            input: VITE_ENTRYPOINTS.map(entry => resolve(rootPath, entry)),
        },
        emptyOutDir: true,
        outDir: resolve(rootPath, VITE_OUTPUT_PATH),
    },
    publicDir: false
})
```

frontend/sandbox/scss/theme/_icons.scss
````
@font-face {
  font-family: 'Unicons';
  src: url("/public/assets/fonts/unicons/Unicons.woff2") format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
````

serve leads to a 404
https://some.test/public/assets/fonts/unicons/Unicons.woff2

and here's the manifest.json from the build
````
{
  "main.css": {
    "file": "assets/main-fbcf4a4b.css",
    "src": "main.css"
  },
  "main.js": {
    "assets": [
      "assets/blob-f8762b71.svg",
      "assets/hex-1e80551c.svg",
      "assets/blob2-68be0ae7.svg",
      "assets/Unicons-7f25d712.woff2"
    ],
    "css": [
      "assets/main-fbcf4a4b.css"
    ],
    "file": "assets/main-be58402f.js",
    "isEntry": true,
    "src": "main.js"
  },
  "public/assets/fonts/unicons/Unicons.woff2": {
    "file": "assets/Unicons-7f25d712.woff2",
    "src": "public/assets/fonts/unicons/Unicons.woff2"
  },
  "public/assets/img/svg/blob.svg": {
    "file": "assets/blob-f8762b71.svg",
    "src": "public/assets/img/svg/blob.svg"
  },
  "public/assets/img/svg/blob2.svg": {
    "file": "assets/blob2-68be0ae7.svg",
    "src": "public/assets/img/svg/blob2.svg"
  },
  "public/assets/img/svg/hex.svg": {
    "file": "assets/hex-1e80551c.svg",
    "src": "public/assets/img/svg/hex.svg"
  }
}
````

I'm using the public folder here, which seems not that great and every doc says it should not be used here?

**Comment by fgeierst** [comment]
@helhum hinted he had best results when placing the vite config file into the project root folder `/vite.config.js`.

**Comment by s2b** [comment]
@fjacobi Aah, I see. I would always advise to use relative paths in your (s)css files to refer to font files. Then vite will copy the font files, change the paths during bundling and it should work.

For example:

```css
@font-face {
  font-family: 'Unicons';
  src: url("../fonts/unicons/Unicons.woff2") format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```

@fgeierst With the default configuration of the extension, this shouldn't be an issue anymore. `VITE_TYPO3_ROOT` allows for all paths to be defined relative to the TYPO3 root path in the config file.

**Comment by fjacobi** [comment]
@s2b That was my starting point from the grunt build.
```
src: url("../../fonts/unicons/Unicons.woff2") format('woff2');

frontend/sandbox/scss/theme/_icons.scss
frontend/sandbox/fonts/unicons/Unicons.woff2
```

But with relative paths neither serve nor build resolves paths properly.

**Comment by s2b** [comment]
Maybe this is your issue? :(

https://github.com/vitejs/vite/issues/11012

**Comment by fjacobi** [comment]
@s2b Yep, 100% my issue.

**Comment by s2b** [comment]
That explains a lot, I was testing with plain css (and postcss) and was expecting similar results with scss.

Maybe `publicDir: true` could be a possible workaround for you. You could put the font file in that directory, which will be copied as-is to the output dir. So I think that the paths should be the same in dev and prod.

**Comment by s2b** [comment]
Closing this, as it probably isn't related to the extension.
