### ISSUE TITLE
Best practice to include assets like fonts

### ISSUE THREAD

**Issue by jramke** [s2b/vite-asset-collector#17]
Hey, im searching for a reliable way to also handle assets like fonts with the vite-asset-collector.

With a php scss compiler you can handle EXT links to Fonts stored in your distribution so that the output link uses the `_assets/hashfolder`.

Can you think of a way to handle a similar behavior when the scss file is imported via the `main.entry.js` file to get in use of the HMR Feature from Vite?

I think the most obvious way to go would be to create a `assets` folder in your public dir and use a url like that `url(/assets/fonts)` in the scss, but that kinda looks weird to have a `assets` and `_assets` folder.

Is there a recommended folder structure or have you got any other idea to get that working?

Thanks for your time and the extension.
Joost

**Comment by s2b** [comment]
In general, I would recommend to use relative paths when referencing fonts and other static assets from css files. However, there seems to be a bug in vite concerning scss files, where in certain conditions this isn't possible. We stumbled upon the same issue in #14.

In my use cases, I used postcss and the nesting plugin, so there was no sass involved. In that case you could use a structure like this:

* Resources/Private/
  * JavaScript/
    * Main.entry.js (includes Main.css and possibly other CSS/JS files)
    * Utils.js
    * ...
  * Css/
    * Main.css
  * Fonts/
    * MyFont.woff2
  * Images/
    * MyIcon.svg

In Main.css, you can then use relative paths to reference the files:

```css
background-image: url(../Images/MyIcon.svg);

src: url("../Fonts/MyFont.woff2") format('woff2');
```

If you then set `base` in your `vite.config.js` to an empty string, vite copies the referenced files to the output path and adjusts the paths while still using relative paths.

**Comment by jramke** [comment]
Well this vite issue sucks.

I tried this structure with the default generated vite config where the base is already an empty string and in Production everything works, but in dev the path to the image is still resolved to "packages/mydist/Resources/Private/Images/MyImage.png".

Am i missing something?

**Comment by s2b** [comment]
Okay, my bad. My local setup was different. With an isolated setup, this behaves the same between css and scss files.

I investigated further and stumbled upon `origin` (again). This seems to be necessary in most TYPO3 setups, as URLs will most likely differ between the vite server and TYPO3.

For now you can set `origin` to the uri of your dev server, and it should work just fine:

```js
export default defineConfig({
  server: {
    origin: 'https://typo3-vite-sass.ddev.site:15174',
  },
```

I found a vite issue and left a comment there, hopefully this can be done automatically in the future: https://github.com/vitejs/vite/issues/12597

**Comment by jramke** [comment]
That works like a charm. Thank you!
This also makes the sass issue obsolete.
Hopefully some of the variants you stated out in the comment make it into vite.

**Comment by Joe1am** [comment]
Hi there!

Unfortunately this still doesn't work for me.

When I refernce an Icon in my scss file like `background-image: url(../../Images/MyIcon.svg)` it tries to load the Icon from https://example.ddev.site/Images/MyIcons.svg.
The same issue with Fonts.

I use Typo3 with ddev and the current vite-asset-collector 1.6. as well as the autoOrigin Plugin and sass.

My vite config file is almost the default. Only changed the VITE_ENTRYPOINTS variable. Beside of this issue, compiling my javascript and scss files works fine

**Comment by s2b** [comment]
I think that there are two separate issues here:

* incorrect/missing origin for dev server, which results in image urls to the TYPO3 server (e. g. nginx in DDEV) instead of the vite dev server. This shouldn't be an issue anymore if you use [vite-plugin-auto-origin](https://github.com/s2b/vite-plugin-auto-origin).

* relative paths in scss files. This is a bug in vite itself which doesn't seem to get enough interest to get fixed. From my point of view, there are two workarounds:
    1. Define paths in scss relative to the entryfile (e. g. Main.entry.js) instead of the current scss file
    2. Use [resolve.alias](https://vitejs.dev/config/shared-options.html#resolve-alias) in vite.config.js to define the font directory and then use that alias in your scss file.

Hope this helps!

**Comment by Joe1am** [comment]
Thank you for the promt response! And yes, it helps. My problem was that I referenced the assets relative to the scss files.
