### ISSUE TITLE
11.5 compatibility

### ISSUE THREAD

**Issue by janslu** [s2b/vite-asset-collector#2]
Hi, 

Any reasons it's compatible with version 12 only? It seems to be working ok with small composer.json change - is there something I'm not seeing? 

And thanks for this! I like vite pipeline much better than webpack and this extension seems like the best integration...

**Comment by s2b** [comment]
Nope, not really. I just don't have a v11 installation at the moment. Feel free to provide a PR!

**Comment by s2b** [comment]
Fixed with v1.1.0
