### ISSUE TITLE
Documentation missing about how to reference assets just for certain content-elements

### ISSUE THREAD

**Issue by Moongazer** [s2b/vite-asset-collector#23]
I just started refactoring my setup using this extension which is going quite well so far. All common/global scrips and packages I referenced in the `app.js`, so far so good. But how does it work for assets which are needed only for certain content-elements?

For example, lets say we built a CardSlider content-element using the NPM package `@splidejs/splide`. In my old setup I used Grunt which compiled the related JS file from `Public/JavaScript/Components/my-cardslider.js` to `Public/JavaScript/Components/my-cardslider.min.js`. The Splide library itself was copied by Grunt to `Public/Libs/splidejs/` including all resources like theme CSS files.

Than in the template I could just reference the assets and they was loaded only if such a content-element was placed on a page.

`Private/Templates/ContentElements/CardSlider.html`:
```
<f:asset.css identifier="splidejs-css" href="EXT:my_site/Resources/Public/Libs/splidejs/css/themes/splide-skyblue.min.css" />
<f:asset.script identifier="splidejs-js" type="module" src="EXT:my_site/Resources/Public/JavaScript/Components/my-cardslider.min.js" />
```

Using the vite-asset-collector, I tried the following:

`assets/JavaScript/Components/my-cardslider.js`:
```
import Splide from '@splidejs/splide'
import '@splidejs/splide/css/skyblue'

// ... init all card-slider elements ...
// const cardSliders = document.querySelectorAll('.mz-cardslider')
// ...
```

Now, referencing it in the content-element template does not work, at least not for production, because the `manifest.json` is missing the `my-cardslider`-asset.
```
<!-- this works only in development context, because the file is loaded directly from original source -->
<vac:asset.vite manifest="EXT:mz_website/Resources/Public/manifest.json" entry="assets/JavaScript/Components/my-cardslider.js" />
```

A workaround is to import the `my-cardslider.js` inside the `app.js`, but than it is loaded always and everywhere, even if it's not needed. How is it possible to solve this issue?

**Comment by s2b** [comment]
From my point of view, there are two options for this:

* server-side: specify your cardslider as a separate entrypoint in vite.config.js
* client-side: use dynamic import in your main entrypoint to load your cardslider only if a cardslider element is present in DOM

See best practices here:
https://notes.typo3.org/s/2hbFMWDVi

And I agree: There should be a collection of best practices somewhere in the documentation (or as a blog post, I'm not sure yet)

**Comment by Moongazer** [comment]
Thank you for the fast response! These notes are very helpful, haven't seen them yet (actually I'd like to have them in the docs). I tried the client-side implementation with dynamic-import which IMO makes most sense for such projects.

But not sure if the given example is right?! Its a bit confusing first including `Componts/**` but than excluding `Organism/Slider/`, which in this example is located in `Components/Organism/Slider/Slider.js`. What does it mean exactly? Maybe you can explain a few words more what happens here. Just guessing: some components are always included, but not if they are located in another sub-folder or so?
```
import.meta.glob([
    "../Components/**/*.{css,js}",
    '!**/Organism/Slider/*'
], { eager: true })
```

**Comment by s2b** [comment]
> Thank you for the fast response! These notes are very helpful, haven't seen them yet (actually I'd like to have them in the docs).

Yes, but I guess I need to think about documentation structure first.

> But not sure if the given example is right?! Its a bit confusing first including `Componts/**` but than excluding `Organism/Slider/`, which in this example is located in `Components/Organism/Slider/Slider.js`. What does it mean exactly? Maybe you can explain a few words more what happens here. Just guessing: some components are always included, but not if they are located in another sub-folder or so?

My setup creates one bundle that includes all component css/js except for the slider (which has much more js and css than any other component). Thus, I exclude those files from the main bundle and create a separate bundle with only those files. This bundle is included with the vite ViewHelper in the slider component template.

**Comment by Moongazer** [comment]
OK understand, but than I ask different: In the notes for me the topic "Split your bundle to load certain resources on-demand" is not clear yet, if "Manual bundle selection with import.meta.glob" and "Dynamic imports" are 2 alternatives and a dev can chose the one or the other? Or are both points needed to archive the goal? Also, in which file is the code of "Create separate bundle" and "Dynamic imports" stored, is there some more configuration needed in the `vite.config.js` to create a separate bundle or so?

Sorry for so many questions, I'm familiar with node/npm/webpack and stuff, but not super in deep, so this information are probably helpful for other developers too which are less firm with these technologies :-)

**Comment by s2b** [comment]
> Sorry for so many questions, I'm familiar with node/npm/webpack and stuff, but not super in deep, so this information are probably helpful for other developers too which are less firm with these technologies :-)

That's the reason why I'm leaning more towards a tutorial/blog post than a reference documentation. :D

The two approaches are two ways to accomplish more or less the same thing. You can use one of them or you can combine them if that makes sense. Usually you would choose one and use only that one.

The client-side solution should work without any vite changes. For the server-side solution, you need to add a second entry point to your vite config. If you use the generated vite config from this extension, you need to modify `VITE_ENTRYPOINTS`:

```js
const VITE_ENTRYPOINTS = [
    "packages/myext/Resources/Private/JavaScript/Main.entry.js",
    "packages/myext/Resources/Private/JavaScript/Slider.entry.js",
];
```

In the end, it's just another array entry in `build.rollupOptions.input`.

As a convention, it can make sense to have a separate `.entry.js` file for each entrypoint, whose task is only to collect other assets (js libraries, your js files, your css files...).

**Comment by Moongazer** [comment]
> That's the reason why I'm leaning more towards a tutorial/blog post than a reference documentation. :D

Wouldn't mind that too, probably its easier to cover more different use-cases with examples 🙂
Anyway, thanks a lot for your fast answers, and for contributing this extension! (I leave closing this issue up to you, in case you want to have it open as reminder)

**Comment by s2b** [comment]
The documentation has been amended to cover much more use cases. Also, a tutorial-style "getting started" chapter has been added.

https://docs.typo3.org/p/praetorius/vite-asset-collector/main/en-us/Installation/Index.html#getting-started
