### ISSUE TITLE
Default Location of the manifest changes in vite 5?

### ISSUE THREAD

**Issue by tobiasquadflieg** [s2b/vite-asset-collector#25]
The new default location of the vite 5 manifest is now in /.vite/manifest.json

[vite 5 doc]( https://vitejs.dev/config/build-options.html#build-manifest)
[vite 3 doc](https://v3.vitejs.dev/config/build-options.html#build-manifest)

So the ViteService needs to search 1 lvl up for the assets.

**Comment by s2b** [comment]
Thank you for making me aware of this change! Can you check if #26 solves this for you?

**Comment by tobiasquadflieg** [comment]
#26 solve the issue!
