### ISSUE TITLE
Add CSS sourcemap settings to initial config

### ISSUE THREAD

**Issue by rintisch** [s2b/vite-asset-collector#29]
At the moment the generated `vite.config.js` file does not contain the option [css.devSourcemap](https://vitejs.dev/config/shared-options.html#css-devsourcemap). This setting is very useful when writing CSS because it's much easier to find the file and the line where the styling comes from.
**Without** this option:
![image](https://github.com/s2b/vite-asset-collector/assets/44193208/4a3a0654-2b9a-4a1c-8c09-41ce5e36a29f)

**With** this option:
![image](https://github.com/s2b/vite-asset-collector/assets/44193208/ef4d4788-393e-4eb2-b100-027107d20d86)

As I can see it just needs to be added to all files in `EXT:vite_asset-_ollector/Resources/Private/ViteConfigTemplates`. I guess in alphabetical order? I could create a PR.

**Comment by s2b** [comment]
I'm always a bit hesitant when extending the default config because I want to keep it simple. But this change makes sense for a lot of people.

So if you have the time, feel free to create a PR for that. Thanks! :)
