### ISSUE TITLE
export default $m();

### ISSUE THREAD

**Issue by chwessalowski** [s2b/vite-asset-collector#53]
Hello Simon
after T3 Camp zurich I gave it a go with this cool extension.
Thank you very much.

However after running "ddev npm exec vite build" I have in my generated JS file the following last line which produces an error in the JS console: export default $m();

Any idea how to prevent this output. I don't think this line of code is necessary. It does not come from my own JS files.  So it must be from a node / vite module?

Thanks in advance for your help.

**Comment by s2b** [comment]
Mh, I don't know what this could be... I use the default configuration the extension generates for my website and the result currently looks like this:

```js
class s extends HTMLElement{constructor(){super(),this.querySelectorAll("[data-formfield=contactType] input").forEach(t=>{t.checked&&this.updateFormState(t.value),t.addEventListener("change",a=>this.updateFormState(a.target.value))})}updateFormState(e){this.setAttribute("state",e)}}customElements.define("sp-contact-request",s);
```
(https://www.praetorius.me/_assets/vite/assets/Main.entry-xnNNVhj-.js?1713183222)

So it must be either something in one of your scripts or a change in the vite config (like a plugin) that leads to this error.

**Comment by s2b** [comment]
Let me know if this is really an issue with the extension or the generated vite config.
