### ISSUE TITLE
Allow TypeScript entry point 

### ISSUE THREAD

**Issue by fgeierst** [s2b/vite-asset-collector#7]
While [Vite comes with TypeScript support](https://vitejs.dev/guide/features.html#typescript), the `asset.vite` viewhelper does not allow .ts files.

```html
    <vac:asset.vite
        manifest="EXT:site-distribution/Resources/Public/manifest.json"
        entry="assets/JavaScript/app.ts"
    />
```
<img width="1160" alt="Bildschirmfoto 2023-07-30 um 10 20 20" src="https://github.com/s2b/vite-asset-collector/assets/22551442/44786dbe-5895-4cbb-9cf2-040ab1c3ca6c">

**Comment by s2b** [comment]
I just tested this in your [typo3-lit-demo](https://github.com/fgeierst/typo3-lit-demo) project and it worked fine. Did you maybe forgot to rebuild in-between changing the file extension?

In general, I didn't implement any limitation here. As long as an entry exists in the manifest file and has `isEntry` set to `true`, it should work.

**Comment by fgeierst** [comment]
Confirmed, it [does work](https://github.com/fgeierst/typo3-lit-demo/commit/70e519842aef1d2aa4010fde3244624e4b971d74) with the TypeScript entry file. Thanks for looking into and sorry for the confusion!
