### ISSUE TITLE
Building assets for production doesn't work

### ISSUE THREAD

**Issue by jackwilliams79** [s2b/vite-asset-collector#80]
Hi,

Im running TYPO3 v13.4 in a DDEV environment and I want to build my JS and CSS assets with Vite. I've installed this extension via composer (version 1.11.0) and also installed the ddev plugin [ddev-vite-sidecar](https://github.com/s2b/ddev-vite-sidecar) and set everything up as described int he documentation (https://docs.typo3.org/p/praetorius/vite-asset-collector/main/en-us/Introduction/Index.html).

When I run `ddev vite` I can see that the assets are loaded correctly in the frontend of my TYPO3 site.

But when I try to build the assets via `npm exec vite build` for the production environment the build process aborts with the follwing error message:

```bash
# Executed in the root of the typo3 project directory
$ npm exec vite build

vite v5.4.9 building for production...
✓ 0 modules transformed.
x Build failed in 7ms
error during build:
Could not resolve entry module "index.html".
    at getRollupError (file:///my_typo3_website/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
    at error (file:///my_typo3_website/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
    at ModuleLoader.loadEntryModule (file:///my_typo3_website/node_modules/rollup/dist/es/shared/node-entry.js:20027:20)
    at async Promise.all (index 0)
```

This is what my project directory looks like (abbreviated):
```
/my_typo3_website/
|- composer.json
|- package.json
|- vite.config.js
|
|- packages/
   |- sitepackage/
      |- Configuration/
         |- ViteEntrypoint.json
      |- Resources/
         |- Public/JavaScript/Main.entry.js
         |- Private/Templates/Layout/Default.html
```

vite.config.js
```js
import { defineConfig } from "vite";
import typo3 from "vite-plugin-typo3";

export default defineConfig({
  plugins: [typo3()],
});
```

ViteEntrypoint.json
```
[
  "../Resources/Public/JavaScript/Main.entry.js"
]
```

Default.html
```html
<html
  data-namespace-typo3-fluid="true"
  xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
  xmlns:vac="http://typo3.org/ns/Praetorius/ViteAssetCollector/ViewHelpers"
>

<vac:asset.vite
  entry="EXT:sitepackage/Resources/Public/JavaScript/Main.entry.js" />
```

Main.entry.js
```js
console.log("Vite says Hello World");
```

As you can see, I've kept the default configuration for manifest and output directory.

What could be the issue?

**Comment by s2b** [comment]
My first guess would be: The file should be named `ViteEntrypoints.json` (plural). So vite doesn't find any entrypoints and defaults to an `index.html`, which doesn't exist.

**Comment by jackwilliams79** [comment]
You are right. That small typo was the mistake. Thank you very much! :smiley:
