### ISSUE TITLE
Injection in ViewHelper is problematic for phpunit functionnal tests

### ISSUE THREAD

**Issue by asakurayoh** [s2b/vite-asset-collector#85]
Hi.
Not sure if there is a problem on how I test my things, but I get this error when running my functionnal tests (with TYPO3 testing-framework): 
Error: Typed property Praetorius\ViteAssetCollector\ViewHelpers\Asset\ViteViewHelper::$viteService must not be accessed before initialization

I'm in TYPO3 v12. 

I use "executeFrontendSubRequest" to call my pages to get the body and test against the result.

**Comment by s2b** [comment]
Thank you for this report. Unfortunately, I currently don't have a similar setup to test this. It seems to be a problem with dependency injection in the sub-request. So first some general questions:

* do you use the latest version of the testing-framework (probably `^8` for TYPO3 v12)?
* do you set any special configuration in your test cases?
* do other ViewHelpers with DI work, like `<f:asset.script />`, which injects `AssetCollector`?
* do other ViewHelpers that use TYPO3 services work, like `<f:image />`, which uses `GeneralUtility::makeInstance(ImageService::class)`?

**Comment by asakurayoh** [comment]
- Yes, I have updated the testing-framework to 8.2.3 to validate there was not a bug already fixed.
- It's in a demo site pretty simple, no special configuration.
- I have tested with `<f:asset.css>` and use a css in my sitepackage. (it also inject `AssetCollector`) and not problems.
- I have also use f:image, and no problem too.

My setup is a very simple simple from which we start our project, nothing fancy.
My tests really just check that a text is show on an VERY basic page (It really just examples of tests).
I've just reviewed some core tests and I seem to do it correctly. I've validate your ViewHelper and the injection and has it is from a ViewHelperInterface, normally the injection is activated (public: true). So not sure where is the problem :/

Thanks!

**Comment by s2b** [comment]
And the extension is loaded in your test using `testExtensionsToLoad`?

**Comment by asakurayoh** [comment]
Ho. I didn't think of that!
Yeah, now t hat work. 

I now have `Praetorius\ViteAssetCollector\Exception\ViteException: Vite manifest file "_assets/vite/.vite/manifest.json" was resolved to "/var/www/html/public/typo3temp/var/tests/functional-ae0ef2a/_assets/vite/.vite/manifest.json" and cannot be opened. ` but that is understandable...
Thanks for the help!

**Comment by asakurayoh** [comment]
Ok, I finally got it to work.
If to help someone:

1. In my functionnal test, add the extension `vite_asset_collector` to `$testExtensionsToLoad`
2. Create a fixture for the `manifest.json` file in `Tests/Fixtures/manifest.json`:
```json
{
    "Main.entry.js": {
        "css": [],
        "file": "",
        "isEntry": true,
        "src": ""
    }
}
```
3. Use `$pathsToProvideInTestInstance` to copy the manifest: 
```php
protected array $pathsToProvideInTestInstance = [
        'typo3conf/ext/site_package/Tests/Fixtures/manifest.json' => 'fileadmin/Fixtures/manifest.json',
    ];
```
4. Set the extesnion configuration to use this manifest:
```php
$this->get(ExtensionConfiguration::class)->set('vite_asset_collector', [
    'useDevServer' => '0',
    'devServerUri' => 'https://localhost:5173',
    'defaultManifest' => 'fileadmin/Fixtures/manifest.json',
]);
```
5. Now the frontend will load the manifest.json in Fixtures without real files in it, but it works.

I don't think there is a "good" way to fix this with the actual code. Something in the viewhelper that could just ignore everything if set; like a "ignore" configuration?

Thanks.

**Comment by s2b** [comment]
You could also enable the dev server, then probably no files need to exist.
